version: '3.1'

services:
  postgres:
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: SilverLight
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data